version: '3.8'

services:
  node-app:
    build: .
    image: starter-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/starter
    ports:
      - '8085:8085'
    depends_on:
      - mongodb
    volumes:
      - .:/src
    networks:
      - starter-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - starter-network

volumes:
  dbdata6:

networks:
  starter-network:
    driver: bridge